Fix retries: Request body disappears in retries (#23)
When first request fails, the subsequent requests with a body fail with:
```
Error: error creating team: Post "http://localhost:3000/api/teams": http: ContentLength=45 with Body length 0
```
This is because the body is consumed in the `t.Transport.RoundTrip(req)` function